@startuml
'https://plantuml.com/object-diagram

title RogueLike - Diagramme d'Objets (Instance du jeu)

object "mainApp : MainApplication" as mainApp {
  WINDOW_WIDTH = 1024
  WINDOW_HEIGHT = 576
}

object "gameScene : GameScene" as gameScene {
  isGameOver = false
  isPaused = false
  currentWave = 1
  demonKillCount = 0
  remainingDemonsToSpawn = 1
  isWaveInProgress = true
  hasPotion1 = false
  hasPotion2 = false
  isJumping = false
  verticalVelocity = 0
  startTime = 1234567890
  lastDamageTime = 0
}

object "wizard : Wizard" as wizard {
  x = 400
  y = 300
  currentHealth = 100
  maxHealth = 100
  attackDamage = 20
  speed = 3.0
  isSpecialActive = false
  isLightningActive = false
  specialAbilityEndTime = 0
  lastSpecialAbilityTime = 0
  attackCooldown = 1000
}

object "dragon1 : Dragon" as dragon1 {
  x = 200
  y = 250
  currentHealth = 50
  maxHealth = 50
  attackDamage = 5
  speed = 0.8
  velocityY = 0.4
  isAttacking = false
  lastAttackTime = 0
  lastDamageTime = 0
}

object "saveData : SaveData" as saveData {
  playerClass = "WIZARD"
  currentWave = 1
  currentHealth = 100
  demonKillCount = 0
  playTime = 4
  hasPotion1 = false
  hasPotion2 = false
}

mainApp --> gameScene
gameScene --> wizard : "player (classe actuelle = Wizard)"
gameScene --> dragon1 : dragons
gameScene --> saveData : currentSave

note right of wizard : "Magicien : DPS à distance avec\nattaque éclair"
note right of dragon1 : "Premier démon\nactif dans la vague"
note bottom of saveData : "État de la sauvegarde\nactuelle"

@enduml
